# Generated by Django 2.1 on 2018-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0004_migrate_old_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryshorthand',
            name='id',
        ),
        migrations.AlterField(
            model_name='queryshorthand',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
