# Generated by Django 2.1 on 2018-10-10 05:16

import crossbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0005_cbuser_crossbucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='emoji_str',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=crossbot.models._item_image_upload_path),
        ),
    ]
