# Generated by Django 2.1 on 2018-10-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0005_cbuser_crossbucks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbuser',
            name='hat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemownershiprecord',
            name='item',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
