# Generated by Django 2.1 on 2018-10-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0006_auto_20181012_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrossbotSettings',
        ),
    ]
